<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>

    <!-- Applica app.manifest solo in build Windows -->
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <!-- Icona dell'eseguibile -->
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>

    <!-- OTTIMIZZAZIONI PER NATIVE AOT & AVVIO ISTANTANEO (<50ms) -->
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
    <OptimizationPreference>Speed</OptimizationPreference>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" Version="7.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="../PatternTester.Core/PatternTester.Core.csproj" />
    <ProjectReference Include="../PatternTester.Rendering/PatternTester.Rendering.csproj" />
    <ProjectReference Include="../PatternTester.Infrastructure/PatternTester.Infrastructure.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <Content Include="Assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <AvaloniaResource Include="Assets\icon.ico" />
    <AvaloniaResource Include="Assets\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Languages\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
